name: Goldbees Trader

on:
  schedule:
    # 09:15 IST == 03:45 UTC (Mon-Fri)
    - cron: "45 3 * * 1-5"

permissions:
  contents: read

concurrency:
  group: goldbees-trader
  cancel-in-progress: false

jobs:
  trade:
    runs-on: ubuntu-latest
    timeout-minutes: 360   
    env:
      TIMEZONE: Asia/Kolkata
      RUN_MODE: LIVE
      END_TIME_IST: "15:00"        # End trading at 3:00 PM IST
      TICKER: GOLDBEES
      # Secrets
      GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      GENERATOR_API_KEY: ${{ secrets.GENERATOR_API_KEY }}
      GENERATOR_TOTP_SECRET: ${{ secrets.GENERATOR_TOTP_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      SHEET_NAME: ${{ secrets.SHEET_NAME }}
      LOOP_FREQ_SECONDS: ${{ secrets.LOOP_FREQ_SECONDS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib requests pyotp gspread oauth2client holidays growwapi

      - name: Skip if holiday, weekend, or market closed
        run: python scripts/market_check.py

      - name: Download private generator script from Google Drive
        run: python scripts/runner.py --download-only

      - name: Run generator
        run: python scripts/runner.py --run
